<script>
  export let active = false
  export let altText = ''
  export let imageUrl = ''
  export let live = false
  export let latencyMs = 0
</script>

<div class="relative rounded-lg overflow-hidden">
  <img
    src={imageUrl}
    alt={active ? altText : ''}
    class="w-full h-48 object-cover transition-all duration-300"
    class:outline={!active}
    class:outline-2={!active}
    class:outline-dashed={!active}
    class:outline-red-500={!active}
    class:outline-green-500={active}
    style="outline-offset: -2px"
  />

  {#if !active}
    <div class="absolute bottom-2 left-2 bg-red-500 text-white text-xs px-2 py-1 rounded font-mono" aria-hidden="true">
      alt=""
    </div>
  {/if}

  {#if active}
    <div class="mt-2 p-3 bg-green-50 border border-green-200 rounded-lg text-sm text-green-900 transition-all duration-300">
      <span class="font-semibold">Alt text:</span> {altText}
      {#if live}
        <span class="ml-2 text-xs text-green-600">(live · {latencyMs}ms)</span>
      {:else}
        <span class="ml-2 text-xs text-green-600 bg-green-100 px-1.5 py-0.5 rounded">generated by Claude</span>
      {/if}
    </div>
  {/if}
</div>
