<script>
  export let active = false
  export let jargonText = ''
  export let plainText = ''
  export let live = false
  export let latencyMs = 0
</script>

<div class="relative">
  <p
    class="text-sm leading-relaxed transition-all duration-500 p-3 rounded-lg"
    class:text-gray-400={!active}
    class:text-xs={!active}
    class:italic={!active}
    class:bg-yellow-50={active}
    class:border={active}
    class:border-yellow-200={active}
    class:text-gray-800={active}
  >
    {active ? plainText : jargonText}
  </p>

  {#if active}
    <div class="mt-1 text-xs text-yellow-700 flex items-center gap-1">
      <span>✓ Simplified to Grade 6</span>
      {#if live}
        <span class="text-yellow-600">· live · {latencyMs}ms</span>
      {:else}
        <span class="bg-yellow-100 px-1.5 py-0.5 rounded">generated by Claude</span>
      {/if}
    </div>
  {/if}
</div>
